# Generated by Django 5.1.2 on 2025-11-06 05:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('estimated_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('estimated_recovery_notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicecategory')),
                ('components', models.ManyToManyField(blank=True, related_name='device_models', to='education.hazardouscomponent')),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='DeviceMaterialEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('estimated_mass_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_estimates', to='devices.devicemodel')),
            ],
            options={
                'ordering': ['material_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_device_name', models.CharField(blank=True, help_text='Provide the device name if it is not listed.', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting Drop-off'), ('received', 'Received'), ('credited', 'Credited'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('estimated_precious_metal_mass', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='In grams', max_digits=9)),
                ('estimated_credit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('message_to_facility', models.CharField(blank=True, max_length=280)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='devices.devicemodel')),
                ('drop_off_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_submissions', to='facilities.facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
