# Generated by Django 5.1.2 on 2025-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardousComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('hazard_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='moderate', max_length=20)),
                ('overview', models.TextField(help_text='High-level explanation of the component risk.')),
                ('environmental_impact', models.TextField()),
                ('human_health_impact', models.TextField()),
                ('safe_handling_guidance', models.TextField(blank=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('module_type', models.CharField(choices=[('awareness', 'Awareness'), ('action', 'Actionable Guidance'), ('deep_dive', 'Deep Dive')], default='awareness', max_length=20)),
                ('estimated_read_time', models.PositiveIntegerField(default=3, help_text='In minutes')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('components', models.ManyToManyField(related_name='modules', to='education.hazardouscomponent')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
