# Generated by Django 5.1.2 on 2025-11-06 05:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('partner_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('points_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfillment_notes', models.TextField(blank=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_redemptions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='accounts.userprofile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rewards.reward')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
